### ISSUE TITLE
Opener APL Issue

### ISSUE THREAD

**Issue by YawnsGithub** [balance-simc/Balance-SimC#4]
In the APL file balance.txt, the opener comment reads "Precast 2 wrath and a surge if below 4 targets".  However the following APL reads like so:

actions.precombat+=/wrath
actions.precombat+=/wrath
actions.precombat+=/starfire

If I am not misunderstanding the APL format, either the comment is wrong or the starfire should be replaced with a starsurge.

**Comment by gastank** [comment]
The APL is correct. Comments fixed in e949ae7
