### ISSUE TITLE
Incorrect stack values in recent commit.

### ISSUE THREAD

**Issue by Ganom** [balance-simc/Balance-SimC#5]
In commit https://github.com/balance-simc/Balance-SimC/commit/3095fd08258a61fb35c946715a85585f942ff88e stack values were changed to stack, but the stack value wasn't modified, resulting in the check only validating at above 30 stacks.

Specifically, line 25 and 26.

**Comment by gastank** [comment]
thanks for the report, fixed in 2e50aa5
